### ISSUE TITLE
  Unhandled exception rendering component: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'System.Net.Http.HttpMethod'.

### ISSUE THREAD

**Issue by ElanHasson** [web-scheduler/web-scheduler-frontend#45]
### Describe the bug

Errors at runtime:

```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'System.Net.Http.HttpMethod'. Path: $.items[0].httpTriggerProperties.httpMethod | LineNumber: 0 | BytePositionInLine: 558.
System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'System.Net.Http.HttpMethod'. Path: $.items[0].httpTriggerProperties.httpMethod | LineNumber: 0 | BytePositionInLine: 558.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'System.Net.Http.HttpMethod'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& , Utf8JsonReader& , NotSupportedException )
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type , Utf8JsonReader& , ReadStack& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[System.Net.Http.HttpMethod, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , HttpMethod& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Net.Http.HttpMethod, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , HttpMethod& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Net.Http.HttpMethod, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[WebScheduler.Abstractions.Grains.Scheduler.HttpTriggerProperties, WebScheduler.Abstractions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , HttpTriggerProperties& )
   at System.Text.Json.Serialization.JsonConverter`1[[WebScheduler.Abstractions.Grains.Scheduler.HttpTriggerProperties, WebScheduler.Abstractions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , HttpTriggerProperties& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[WebScheduler.Abstractions.Grains.Scheduler.HttpTriggerProperties, WebScheduler.Abstractions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , ScheduledTask& )
   at System.Text.Json.Serialization.JsonConverter`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , ScheduledTask& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , List`1& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , List`1& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.Collections.Generic.List`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[WebScheduler.Api.Models.ViewModels.PageResults`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , PageResults`1& )
   at System.Text.Json.Serialization.JsonConverter`1[[WebScheduler.Api.Models.ViewModels.PageResults`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , PageResults`1& )
   at System.Text.Json.Serialization.JsonConverter`1[[WebScheduler.Api.Models.ViewModels.PageResults`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[PageResults`1](JsonConverter , Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadCore[PageResults`1](JsonReaderState& , Boolean , ReadOnlySpan`1 , JsonSerializerOptions , ReadStack& , JsonConverter )
   at System.Text.Json.JsonSerializer.ContinueDeserialize[PageResults`1](ReadBufferState& , JsonReaderState& , ReadStack& , JsonConverter , JsonSerializerOptions )
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[WebScheduler.Api.Models.ViewModels.PageResults`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__4`1[[WebScheduler.Api.Models.ViewModels.PageResults`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[WebScheduler.Api.Models.ViewModels.PageResults`1[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]], WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at WebScheduler.FrontEnd.Blazor.Services.ScheduledTaskService.GetPageAsync(PageOptions pageOptions)
   at WebScheduler.FrontEnd.Blazor.Pages.ScheduledTask.Index.OnReadData(DataGridReadDataEventArgs`1 e)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Blazorise.DataGrid.DataGrid`1.<HandleReadData>d__67[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Blazorise.DataGrid.DataGrid`1.<HandleReadData>d__67[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Blazorise.DataGrid.DataGrid`1.<Reload>d__65[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Blazorise.DataGrid.DataGrid`1.<OnAfterRenderAsync>d__31[[WebScheduler.Api.Models.ViewModels.ScheduledTask, WebScheduler.Api.Models, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

### Steps to reproduce

1. Load the app at https://scheduler.nullreference.io
2. Try to create a new task or view list of scheduled tasks

### Expected behaviour

It should work without any errors.

**Comment by ElanHasson** [comment]
Still broken. trying to fix
